title: Tool Bag of Holding
description: One-stop shop for D&D players
github_username: KJ322
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
